# 02.03 Vectors and Matrices

- dot product of two vectors. 
- matrix multiplication and dimensionality
- element wise multiplication with a "scalar" and a vector


In [2]:
import numpy as np

#### --> 1. Create Vectors
* Make a vector (1d array) of 1 to 5 using np.arange
* Make another vector (1d array) of 2,4,6,8,10 using np.linspace
* print each vector

```
a1 = np.arange(<startval>,<uptobutnotincludingval>)
a2 = np.linspace(<startval>,<endval>,<numberofvalues>)
```
**Double Click Here for answer**
<!--
a1 = np.arange(1,6)
a2 = np.linspace(2,10,5)
print("a1 is: ", a1)
print("a2 is: ", a2)
-->


In [4]:

print("a1 is: ", )
print("a2 is: ", )

a1 is:  [1 2 3 4 5]
a2 is:  [ 2.  4.  6.  8. 10.]


### Elementwise multiplication
The * operator does elementwise multiplication.  

*Note that Octave uses .* for elementwise multiplication.*

#### --> 2. Check this out by multiplying your two vectors.

**Double Click Here for answer**
<!--
a1 * a2
-->

array([ 2.,  8., 18., 32., 50.])

### Dot product
The dot product, or matrix multiplication, multiplies two matrices together.

The dot product is the sum of the products of each corresponding element.  Very useful if you have a sum of products in math notation!  E.g. when you see:

$$\sum_{i=1}^{100} x_i * y_i $$

You should think "Vectorize!"

*The dot function works like Octave *  (dot product / matrix multiplication)*

#### --> 3.  Try dot product.
> try np.dot( <yourarray1>,  <yourarray2>)   
    
> try  <yourarray1>  @  <yourarray2> - the @ operator is the same as np.dot
    
**Double Click Here for answer**
<!--
print(np.dot(a1,a2))
print(a1 @ a2)
-->



110.0
110.0


## Matrix Multiplication

Dot product and matrix multiplication are the same as long as you view dot product as multiplying a 1xn vector with a nx1 vector (i.e. you may need to transpose).

But NumPy handles that transpose for you if you should try that.

#### --> 4.  Multiply matrices

* Make a1 that's 1 by 4 with the np.arange function
* Make a2 that's  4 by 2 of counts, using the np.array constructor: [[1,2],[3,4],[5,6],[7,8]]
* Multiply a1 and a2 using the @ operator.

The inner dimensions must match.  The result is the outer dimensions...

You should get a 1x2 that's `[50, 60]`

**Double Click Here for answer**
<!--
a2 =  np.array( [[1,2],[3,4],[5,6],[7,8]] )
a1 = np.array( [ 1,2,3,4] )
a1 @ a2
-->


In [11]:
###
a1 = np.arange( 1,5 )
a2 =  np.array( [[1,2],[3,4],[5,6],[7,8]] )
a1 @ a2

array([50, 60])



What kind of error do you get if you try to multiply mismatched matrices?  Give it a try.

#### --> 5. Try / Except to catch error in NumPy
See if you can use a try / except block to catch the error.

**Double Click Here for answer**
<!--
try:
    a2 @ a1
except ValueError as e:
    print("Error in dimensions \n" + str(e))
-->




In [12]:
###
try:
    a2 @ a1
except ValueError as e:
    print("Error in dimensions " + str(e))

Error in dimensionsmatmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)


# Using Dot Product and Multiplication

Let's walk through an actual example with data, so you can see how to use matrix multiplication usefully to do something practical.

This is an important example because it illustrates the singularly most important concept of all of mathematics.  Dude.  Really?  Yes.  That concept is **abstraction** - the ability to encapsulate meaning in symbols, and then figure out a way to work with those symbols with symbol tools.  And then take the results back to get new meaning.

Dude.

### The problem - Fruit ###
Bananas, apples, and pears are sold at 0.25 cents,  0.80 cents, and 0.60 cents each.  50 people are going to each buy different amounts.    How much does each person spend?

> Abstraction step.  Let's represent what each person spends as a vector. So `[1,3,4]` would mean one banana, 3 apples, 4 pears.

#### --> 6. Create an array, `orders` , of random orders for 50 people.  A 50x3 array.  Also create the prices array, a 1x3 array.

Let's suppose someone may order between 0 and 4 of each fruit. Up to but not including 5.

```
orders = ???
prices = ???

```

**Double Click Here for answer**
<!--
###

# Randomize orders for 50 people
orders = np.random.randint( 5, size=(50,3) )

#Let's set the prices…
prices = np.array( [0.25, 0.80, 0.60] )
-->



In [13]:
#orders = ?
#prices = ?

###

# Randomize orders for 50 people
orders = np.random.randint( 5, size=(50,3) )

#Let's set the prices…
prices = np.array( [0.25, 0.80, 0.60] )



How much does each person spend?

Note that with NumPy Arrays, as you can see, you use `[row, colunn]` to get at a value in there rather than the Python List way of `somelist[row][column]`


#### --> 7. Iterative solution

Naive way first.  Write a for loop to step through the people, and multiply each person's orders by the prices, to get an amount for each person.

*You'll need to initialize the amounts to zero.
*You'll need a for loop to step over each `person` with `range(len(amount))`  or you can also use `range(len(orders))`
*You'll need to calcualte `amount[person]` by multiplying the amount of bananas, `orders[person,0]` with the price of bananas `prices[0]`


**Double Click Here for answer**
<!--
amount = np.zeros(50)
for person in range(len(amount)):
    amount[person] = orders[person,0] * prices[0] + \
                     orders[person,1] * prices[1] +  \
                     orders[person,2] * prices[2]

-->



In [14]:
len(orders)

50

In [22]:
###
amount = np.zeros(50)
for person in range(len(amount)):
    amount[person] = orders[person,0] * prices[0] + \
                     orders[person,1] * prices[1] +  \
                     orders[person,2] * prices[2]

    
# Look I made a cute little table printer.
# IMPORTANT:  Observe how I can slice out the top 5 rows, with the columns.

def printAmounts():
    print("Person...\t  1 2 3 4 5")
    print("Num Bananas: \t", orders[0:5,0])
    print("Num Apples:  \t", orders[0:5,1])
    print("Num Pears:   \t", orders[0:5,2])

    print("Amounts: \t",amount[0:5])

printAmounts()

Person...	  1 2 3 4 5
Num Bananas: 	 [1 3 3 2 1]
Num Apples:  	 [2 3 0 0 4]
Num Pears:   	 [3 2 4 3 2]
Amounts: 	 [3.65 4.35 3.15 2.3  4.65]



Hold on.  Each inner assignment looks like a dot product, to me.

#### --> 8. Replace the inside of the for loop above with a dot prouct between `orders[person]` and `prices`

**Double Click Here for answer**
<!--
amount = np.zeros(50)
for person in range(len(amount)):
    amount[person] = orders[person] @ prices
-->



In [23]:
###
amount = np.zeros(50)
for person in range(len(amount)):
    amount[person] = orders[person] @ prices
    
# Look I used my function from abvoe!
printAmounts()
# Do you get the same thing as before?

Person...	  1 2 3 4 5
Num Bananas: 	 [1 3 3 2 1]
Num Apples:  	 [2 3 0 0 4]
Num Pears:   	 [3 2 4 3 2]
Amounts: 	 [3.65 4.35 3.15 2.3  4.65]


### But wait!

But then ... we can use matrix multiplicaton for the whole thing.

#### --> 9.  Vectorized solution.

*Write a single line of code to compute all of the amounts.
*Write a print statement to print the dimensions of orders and dimensions of the prices tables.

The dimensionality analysis is super critical.

**Double Click Here for answer**
<!--
amount = orders @ prices
print("orders is 50x3.  Prices is 3x1.  Result is 50x1.")
printAmounts()
-->


In [29]:
#amount = orders @ prices
#print("orders is ??? .  Prices is ??? .  Result is ??? .")
printAmounts()
print(f"Shape of orders: {orders.shape} And of prices: {prices.shape}")
###
amount = orders @ prices
print("orders is 50x3.  Prices is 3x1.  Result is 50x1.")
printAmounts()

Person...	  1 2 3 4 5
Num Bananas: 	 [1 3 3 2 1]
Num Apples:  	 [2 3 0 0 4]
Num Pears:   	 [3 2 4 3 2]
Amounts: 	 [3.65 4.35 3.15 2.3  4.65]
Shape of orders: (50, 3) And of prices: (3,)
orders is 50x3.  Prices is 3x1.  Result is 50x1.
Person...	  1 2 3 4 5
Num Bananas: 	 [1 3 3 2 1]
Num Apples:  	 [2 3 0 0 4]
Num Pears:   	 [3 2 4 3 2]
Amounts: 	 [3.65 4.35 3.15 2.3  4.65]


## NumPy Sum

Now we can sum up the amounts spent by each person, and on each type of fruit.  Note that `np.sum(amount)` is the same as using the `sum` method of the `amount` NumPy Instance:  `amount.sum()`

By default, `sum` iterates over the rows.  That's called the **axis** of the sum.  So if you have a 50x3 array of orders, summing over the orders with axis 0 (summing rows) will give you a 1x3 result.  You can specify an axis of 1 and sum over columns, which would give you a 50x1 result.  What would that represent in this case?  

#### --> 10.  Summing by rows and columns

Part 1:
* Change the code below to use amount.sum() instead of np.sum(amount...)
* Calculate a new variable `totalCounts` to get the total number of each kind of fruit.
* Use a list comprehension of format strings to print the number of each fruit above.

**Double Click Here for answer**
<!--
# Using amount.sum instead of np.sum(amount) ... note axis=0 is optional.  0 is the default.
print(f"Total spent: {amount.sum(axis=0):0.2f}")

totalCounts = np.sum(orders, axis=0) 
print(totalCounts, "bananas, appples, pears")

-->


In [45]:
print(f"Total spent: {np.sum(amount):0.2f}")

###
print(f"Total spent: {amount.sum(axis=0):0.2f}")
totalFruitsPerPerson = orders.sum(axis=1)
print( "First 5 people ate: ", [x for x in totalFruitsPerPerson[0:5]], " Fruits.")
totalCounts = np.sum(orders, axis=0) 
print(totalCounts, "bananas, appples, pears")
fruitTotals = totalCounts * prices
print(fruitTotals, 'total spent on bananas, apples, pears')
# super fancy way:
print( ", ".join(map( lambda x,y : f"{x}: ${y:0.2f}", ['bananas', 'apples', 'pears'], fruitTotals)) )


Total spent: 173.15
Total spent: 173.15
First 5 people ate:  [6, 8, 7, 5, 7]  Fruits.
[107 102 108] bananas, appples, pears
[26.75 81.6  64.8 ] total spent on bananas, apples, pears
bananas: $26.75, apples: $81.60, pears: $64.80


Part 2:
* Calculate a new variable `totalFruitsPerPerson` to sum the total number of fruits each person ate. Use axis 1.  Print the first 5 with a list comprehension and a slice of `totalFruitsPerPerson`
* Use elementwise multiplication to get the total spent on each type of fruit, `fruitTotals`
* Print the `fruitTotals` result.

**Double Click Here for answer**
<!--
totalFruitsPerPerson = orders.sum(axis=1)
print( "First 5 people ate: ", [x for x in totalFruitsPerPerson[0:5]], " Fruits.")

fruitTotals = totalCounts * prices
print(fruitTotals, 'total spent on bananas, apples, pears')
# super fancy way:
print( ", ".join(map( lambda x,y : f"{x}: ${y:0.2f}", ['bananas', 'apples', 'pears'], fruitTotals)) )

-->

(50, 3)